### ISSUE TITLE
PEM - private key

### ISSUE THREAD

**Issue by carloseguevara** [KenN7/vim-arsync#16]
Hi, I really love to use your plugin, but now I need to connect to one EC2 using a PEM file or private key. Already exists some way to specify the path of the pem file to create the remote connection?

I know that the console rsync command have one way with the e flat:
rsync -avz -e "ssh -i miclave.pem" /local/path/ usuario@remoto:/remote/path

**Comment by KenN7** [comment]
Hi there :)

Thanks for your interrest, and sorry for the late answer,
for now i don't have an immediate solution for selecting the key, it would require a change in the code.

However, as a workaround you could specify the location of your private key in your `~/.ssh/config` file like so:

```
Host github.com
  User git
  Hostname github.com
  IdentityFile ~/.ssh/id_rsa
```

**Comment by KenN7** [comment]
up?
