### ISSUE TITLE
 auto_sync_up 1 is not working after restart.

### ISSUE THREAD

**Issue by foloinfo** [KenN7/vim-arsync#2]
Hi, this plugin is what I needed.

It is working right after I run `:PlugInstall` command with auto_sync_up set to 1 with `.vim-arsync` file configured.
However, when I re-start the nvim it stops working. I can run `:PlugInstall` again to auto sync to work, but I think I'm missing something.

Is there any command that I have to set up in `.vimrc`? or is this intended behavior?

**Comment by KenN7** [comment]
Hi, thx for feedback;
I just tested with last master version, but i cannot reproduce the error.

Note that auto_sync_up only syncs when your buffer is saved (when you do :w).
Did you save your file before checking if the folder was synced ?

If you open the quickfix window ( :copen ) you can check the log of vim-arsync.
Please check if the :ARsyncUp command work.

**Comment by KenN7** [comment]
@foloinfo any follow up ? otherwise i'll close

**Comment by foloinfo** [comment]
@KenN7 I tried with `:copen` to check what's happening.
It seems like arsync is not running right after vim starts.

When I hit `:ARsyncUp` the `:copen` will output

```
|| building file list ... 
|| done
|| components/
|| components/Button.js
|| 
|| sent 4.72K bytes  received 72 bytes  9.59K bytes/sec
|| total size is 1.58M  speedup is 329.44
|| 
|| 
```

However when I hit `:w` after reboot it does nothing.
After I run `:PlugInstall` and hit `:w` then it starts syncing files.

---

I write until here and I suspected if opening vim with directory has effected, so I tried to open withoout any directory and it starts working!

I usually open vim like `nvim .` to open current directory. It seems like arsync is not working this way.
I have to open with `nvim` and navigate inside vim.

Is there any workaround for this issue?

**Comment by KenN7** [comment]
Okay Now i see, 
so basically, if you open a folder, then no auto syncing is activated even after opening a file
if you open a file everything works fine.
I'll check this and keep you updated

**Comment by KenN7** [comment]
I changed to way the auto command is set, it should work now. Let me know.

**Comment by foloinfo** [comment]
@KenN7 I updated to the latest and it's working! Awesome!
