### ISSUE TITLE
Does not transform symlinks

### ISSUE THREAD

**Issue by OscarCreator** [KenN7/vim-arsync#21]
I have a bunch of files which are symlinks on the remote machine, but obviously these links will break once you use ARsyncDown.

One option would then be to transform these remote links to the actual content of the files.

To add this would be quite simple as the `L` option for rsync does exactly this.

**Comment by KenN7** [comment]
Hi! Thanks for all the work, issues and PR, U currently cannot take a look at it before next week, extremely busy week. I'll try my best to check this and merge asap. Thanks again!
