### ISSUE TITLE
Add status or progress bar

### ISSUE THREAD

**Issue by ductri** [KenN7/vim-arsync#7]
Hi, 

I've been using your plugin for a while, and it really helps to increase productivity. But one thing that bothered me is that every time I use ARsyncUp, I have to go to my remote server to check if the code has already changed because there is no indicator from my local vim. So I wonder is it possible to add this feature? Some thing like showing which file has been synced in statusbar or quickfix windows.

I'm very new to Vim Script, but I'm willing to help if there's a need. Thanks.

**Comment by KenN7** [comment]
Hi,
Thanks for the support :)

For now the log is displayed in the quickfix window of vim,
after the syncing command, you can open it with `:copen` and you should see the log,
then close it with `:ccl`.
For sure, adding status in bar could be a good thing to add.

I don't have much time right now, i'll look into it when i do.

**Comment by ductri** [comment]
I found a solution for myself: create a mapping such as
`<localleader>sd :ARsyncDown<cr>:copen<cr><c-w>k` 
then every ARsyncDown will be followed by quickfix window opening at the bottom of current window without losing focus. 

So I guess will close this issue then. Thanks
